[package]
name = "coffer-macros"
version = "1.0.0"
authors = ["Deadbeef"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.24"
quote = "1.0.7"

[dependencies.syn]
version = "1.0.56"
features = ["default", "printing"]
