name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Run Tests
      uses: actions-rs/cargo@v1
      with:
        command: test
    - name: Run Benchmark
      run: cargo +nightly bench | tee output.txt
    - uses: rhysd/github-action-benchmark@v1
      with:
        name: Rust Benchmark
        tool: 'cargo'
        output-file-path: ./output.txt
        github-token: ${{ secrets.GITHUB_TOKEN }}
        alert-threshold: '200%'
        comment-on-alert: true
        alert-comment-cc-users: '@fee1-dead'
    - name: Deploy Benchmark Results
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/criterion
      if: github.event_name != 'pull_request'

